### ISSUE TITLE
How does the redirect for this backend work.

### ISSUE THREAD

**Issue by makkus** [Peter-Slump/django-keycloak#11]
Sorry, this is probably a stupid question, I'm just getting started with Django and its authentication. I'm having trouble figuring out how to 'force' a user login with this app. How would one, for example, create a 'login' button that redirects to Keycloak?

I've tried to do:

    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

In a view, but only redirects to:

http://localhost:8000/path/keycloak_login?next=/path/

I tried to put in the whole url of my keycloak server as value for LOGIN_URL, in settings.py, but then I'm getting an error message saying 'Missing parameters: client_id'

Any advice would be highly appreciated.

Cheers!

**Comment by Peter-Slump** [comment]
Hi @makkus,

I might have forgotten something in the documentation. You also have to configure the Keycloak URL's by adding something like this to your urls.py:

```
urlpatterns = [
    ... some other url configs ...
    url(r'^account/', include('django_keycloak.urls')),
]
``` 

Please don't forget to configure your Keycloak server and REALM using the Django Admin before trying to login.

**Comment by Peter-Slump** [comment]
I've updated the docs.

**Comment by makkus** [comment]
Thanks, much appreciated!

**Comment by VincentSch4rf** [comment]
I just ran into the same issue. Unfortunately, the documentation seems to be outdated again. Instead of  using `keycloak_login` as `LOGIN_URL` one has to use `keycloak/login`.
I hope this helps anyone else trying to get the library up and running. Apart from that minor "bug" very nice job 😄
