### ISSUE TITLE
Django rest framework support

### ISSUE THREAD

**Issue by MiltosD** [Peter-Slump/django-keycloak#30]
Hello, I wonder if this can work with DRF, since I am building a django rest backend and I need to be able to get JWT from keycloak, that would be valid within django rest framework.

Thanks

**Comment by Peter-Slump** [comment]
Sorry did not test it with DRF. But be my guest ;)

**Comment by phoebebright** [comment]
Created a custom backend for drf::
 
     

    class KeycloakDRFAuthorizationBackend(KeycloakAuthorizationBase):
        keyword = "bearer"
    
        def authenticate(self, request):
    
            auth = request.headers.get('Authorization').split()
            provided_origin = request.headers.get('Origin')
    
    
            if not auth:
                return None
    
            elif auth[0].lower() != self.keyword.lower():
                msg = _('Invalid key for Authorization, expecting Bearer')
                raise PermissionDenied(msg)
    
            elif len(auth) == 1:
                msg = _('Invalid token header. No credentials provided.')
                raise PermissionDenied(msg)
            elif len(auth) > 2:
                msg = _('Invalid token header. Token string should not contain spaces.')
                raise PermissionDenied(msg)
    
            try:
                token = auth[1]
            except UnicodeError:
                msg = _('Invalid token header. Token string should not contain invalid characters.')
                raise PermissionDenied(msg)
    
    
            if not hasattr(request, 'realm'):
                raise ImproperlyConfigured(
                    'Add BaseKeycloakMiddleware to middlewares')
    
            try:
                oidc_profile = django_keycloak.services.oidc_profile\
                    .get_or_create_from_id_token(
                        client=request.realm.client,
                        id_token=token
                    )
            except ExpiredSignatureError:
                # If the signature has expired.
                msg = _('KeycloakBearerAuthorizationBackend: failed to '
                             'authenticate due to an expired access token.')
                raise PermissionDenied(msg)
            except JWTClaimsError as e:
                msg = _('KeycloakBearerAuthorizationBackend: failed to '
                             'authenticate due to failing claim checks: "%s"'
                             % str(e))
                raise PermissionDenied(msg)
            except JWTError:
                # The signature is invalid in any way.
                msg = _('KeycloakBearerAuthorizationBackend: failed to '
                             'authenticate due to a malformed access token.')
                raise PermissionDenied(msg)
            except Exception as e:
                msg = _(f'Unexpected error in authentication {e}')
                raise PermissionDenied(msg)
            else:
                return (oidc_profile.user, None)
    
            return None
