### ISSUE TITLE
A tutorial for using Django with keycloack

### ISSUE THREAD

**Issue by nirav3650** [Peter-Slump/django-keycloak#40]
I request @Peter-Slump to please post a tutorial for using django-keycloak with Django version 3.0.3
I googled for tutorial but any of them didn't work

**Comment by srinathganesh1** [comment]
Can you provide the configuration files that you have? 

This is the tutorial that you need 

- https://readthedocs.org/projects/django-keycloak/downloads/pdf/stable/ (CHAPTER 11)
- https://django-keycloak.readthedocs.io/en/latest/scenario/initial_setup.html

**Comment by tomallv** [comment]
Hi, i am learning how to intergrate the keycloack in my project(Django 3.0.4), follow your tutoral, i found that my Django administration page doesn't have Keycloak configuration item, whether this is needed to manually configurate? where can do this? 
Another question: only the "django-keycloak" package is only needed for the whole process? any other packages needed else? thank you!

**Comment by Peter-Slump** [comment]
Hi @tomallv I never tested the package with Django 3+ so I don't know if it will work. I hope to find some time soon to experiment.

**Comment by tomallv** [comment]
@Peter-Slump hope you can get updated tutoral with Django 3+ in soon future, i found another package "Django REST Framework Keycloak" that would be workable from documentation, i will try it later

**Comment by srinathganesh1** [comment]
> Hi, i am learning how to intergrate the keycloack in my project(Django 3.0.4), follow your tutoral, i found that my Django administration page doesn't have Keycloak configuration item, whether this is needed to manually configurate? where can do this?
> Another question: only the "django-keycloak" package is only needed for the whole process? any other packages needed else? thank you!

To begin with I used this with djnago 1.11 (its a old app, thats why) so I cannot speak about djnago 3.

IF you could post your configs and screenshots, I (or someone else) could compare and see whether you are missing something.

> Django administration page doesn't have Keycloak configuration item
- is `INSTALLED_APPS` in settings.py updated?
- can your verify whether database migrations are done? I perform a blanket migration `python3 manage.py migrate`

**Comment by nirav3650** [comment]
Hi,
I want to use keycloack user groups with my Django application how can I do it using django-keycloak.
I followed remote user page of django-keycloak but after that it gives field error.

> Invalid field name given in select_related:oidc_profile. Choices are (none)

**Comment by srinathganesh1** [comment]
> Hi,
> I want to use keycloack user groups with my Django application how can I do it using django-keycloak.
> I followed remote user page of django-keycloak but after that it gives field error.
> 
> > Invalid field name given in select_related:oidc_profile. Choices are (none)

you are generally NOT supposed to use Remote User, unless you are sure you need that functionality

**Comment by nirav3650** [comment]
How can I use groups present in a realm of keycloack with the Django application

**Comment by srinathganesh1** [comment]
> How can I use groups present in a realm of keycloack with the Django application

I think you should be worried about this AFTER a basic connection works

**Comment by nirav3650** [comment]
> > How can I use groups present in a realm of keycloack with the Django application
> 
> I think you should be worried about this AFTER a basic connection works

I am able to authenticate user using keycloack with my Django application

**Comment by tomallv** [comment]
@nirav3650 Is Django 3.+ is used in your side? how did you do the configuration in the settings.py? and is there other packages needed else in your proejct except django_keycloak? i mean just in the keycloak auth workarea.

**Comment by nirav3650** [comment]
> @nirav3650 Is Django 3.+ is used in your side? how did you do the configuration in the settings.py? and is there other packages needed else in your proejct except django_keycloak? i mean just in the keycloak auth workarea.

Hi @tomallv ,
Just follow the Django keycloack setup install page 
In Django settings of your app you need to add keycloack_django in installed apps as suggested in Django keycloack documentation.
No other packages are needed.
Once setup you need to do python manage.py migrate to add keycloack config tables in your Django application

**Comment by srinathganesh1** [comment]
> @nirav3650 Is Django 3.+ is used in your side? how did you do the configuration in the settings.py? and is there other packages needed else in your proejct except django_keycloak? i mean just in the keycloak auth workarea.

if you can post ur config someone could posibly think what the issue can be. without that there hardly anything other can do

**Comment by srinathganesh1** [comment]
> > > How can I use groups present in a realm of keycloack with the Django application
> > 
> > 
> > I think you should be worried about this AFTER a basic connection works
> 
> I am able to authenticate user using keycloack with my Django application

1. does it redirect you to keycloak page?
2. does it redirect back to your django app?
3. does it print any errors?

**Comment by srinathganesh1** [comment]
> > > How can I use groups present in a realm of keycloack with the Django application
> > 
> > 
> > I think you should be worried about this AFTER a basic connection works
> 
> I am able to authenticate user using keycloack with my Django application

i have not used groups

**Comment by tomallv** [comment]
> > @nirav3650 Is Django 3.+ is used in your side? how did you do the configuration in the settings.py? and is there other packages needed else in your proejct except django_keycloak? i mean just in the keycloak auth workarea.
> 
> Hi @tomallv ,
> Just follow the Django keycloack setup install page
> In Django settings of your app you need to add keycloack_django in installed apps as suggested in Django keycloack documentation.
> No other packages are needed.
> Once setup you need to do python manage.py migrate to add keycloack config tables in your Django application

Do this in settings.py 
INSTALLED_APPS = ['django_keycloak.apps.KeycloakAppConfig']
MIDDLEWARE = ['django_keycloak.middleware.BaseKeycloakMiddleware',]

AUTHENTICATION_BACKENDS =['django_keycloak.auth.backends.KeycloakAuthorizationCodeBackend',]

LOGIN_URL = 'keycloak_login'

# your-project/urls.py
urlpatterns = [url(r'^keycloak/', include('django_keycloak.urls')),]

KEYCLOAK_OIDC_PROFILE_MODEL = 'django_keycloak.OpenIdConnectProfile'

and then i config bellow settings:
KEYCLOAK_CONFIG = {
    'KEYCLOAK_SERVER_URL': 'http://xxxxxxxxxx/auth/',
    'KEYCLOAK_REALM': 'xxxxxx',
    'KEYCLOAK_CLIENT_ID': 'xxxxxxxxxx',
    # 'KEYCLOAK_CLIENT_SECRET_KEY': 'secret_key',
    # 'KEYCLOAK_CLIENT_PUBLIC_KEY': 'public_key',
    'KEYCLOAK_DEFAULT_ACCESS': 'DENY', # DENY or ALLOW (Default is DENY)
    'KEYCLOAK_AUTHORIZATION_CONFIG': os.path.join(BASE_DIR,  'your-client-authz-config.json'),
    'KEYCLOAK_METHOD_VALIDATE_TOKEN': 'INTROSPECT', # INTROSPECT OR DECODE (Default is INTROSPECT)
}

any wrong? or any missing?

**Comment by srinathganesh1** [comment]
@tomallv have you run migrations?

**Comment by tomallv** [comment]
@srinathganesh1 yes, this is done, after access the link "http://127.0.0.1:9061/keycloak/login",  one waring pops up
" ......... 
File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\django\views\generic\base.py", line 188, in get
    url = self.get_redirect_url(*args, **kwargs)
  File "C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\django_keycloak\views.py", line 46, in get_redirect_url
    authorization_url = self.request.realm.client.openid_api_client\
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\django\utils\functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'NoneType' object has no attribute 'client'
"

**Comment by srinathganesh1** [comment]
@tomallv can you check ur database, whether new tables are created for this package?

**Comment by nirav3650** [comment]
Is there a way to get the group name to which the user belongs to via Django keycloack

**Comment by tomallv** [comment]
@srinathganesh1 yes, total 8 new tables keycloak related are created as below screenshot:
![image](https://user-images.githubusercontent.com/33150898/78897453-c796de80-7aa4-11ea-87ea-7009e7be9b51.png)
