### ISSUE TITLE
Best way to handle email instead of username

### ISSUE THREAD

**Issue by phoebebright** [Peter-Slump/django-keycloak#41]
I had originally setup my user model to use email for authentication so there was no username field.  I put it back to get keycloak to work and when a user is registered on keycloak I get an entry in the usermodel with a keycloak id in the username and the email completed.  This is fine.

However, if an existing django users tries to register in keycloak there will be an error because django-keycloak is matching on username but a record with this email already exists, so it falls over with duplicate record.

I could of course migrate all the users first, but I would like to use this as an opportunity to not migrate users who are no longer active.

What is the best approach here?
- get keycloak to use email as the key - having a separate id fields that allows the email to be changed seems like a good idea so not keen on that one.  However if I put the email in the username field in django, this should be possible.
- modify django-keycloak to have the option of using email rather than username to identify the user.
- write a custom authenticator that calls a custom oidc_profile that has some customised code.
- something else?!

**Comment by Peter-Slump** [comment]
There are several options as you mentioned. I want to add another option. You can also override the `update_or_create` method on your User model manager. In that way you can first try to find the user by Keycloak ID, then by email. If found by email you can transform the User to a Keycloak version.

Maybe that helps.

Ps. I received an message from you? However there was no reply address in the message so I am not able to respond :( maybe you can try again or send a mail?

**Comment by phoebebright** [comment]
Am avoiding the issue above altogether for the moment by getting users to re-register but may come back to it later and try the update_or_create method you suggest.

Have made good progress so my contact message is no longer relevant.  I have learned a lot and have so far used django-keycloak with a few small modifications.  However am now tackling drf integration issue and have a couple of questions that I will add to the existing ticket on that subject.
