### ISSUE TITLE
Keycloak user getting created on django's users_user table

### ISSUE THREAD

**Issue by sairamkrish** [Peter-Slump/django-keycloak#9]
Hi

I had a similar need and started exploring this project. 
Facing this issue:

The need for using keycloak is to keep user management as a separate layer. After integrating this project and keycloak, when a user, who is created in keycloak Sign-in into django, I see a user record getting created in django's database inside "users_user" table (postgresql, in mycase).

Why do we need user record in django database ? 
It should just consume the access token and understand the permissions from keycloak and allow the user right ?

**Comment by Peter-Slump** [comment]
Hi @sairamkrish,

You are right there is not always a need to store the user in the database. However when you want to link objects to the authenticated user it can be handy to have a record of the user in the database.
Off course you are always welcome to add a option for stateless authentication and create a pull request.

Peter
